[package]
name = "cwe-xml"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.29.0", features = ["serialize"] }
serde = { version = "1.0.164", features = ["derive"] }
thiserror = "1.0.40"
